spring.application.name=ProductFin
spring.datasource.url=jdbc:mysql://localhost:3306/product_fin
spring.datasource.username=root
spring.datasource.password=user
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
server.port=8081